package:
  name: tigre
  version: {{ environ.get('GIT_DESCRIBE_TAG','v')[1:] }}

source:
#  git_rev: 3067d6b9d08875c2bbce4e6f06a5513119353bfe
  git_url: https://github.com/CERN/TIGRE.git
  git_rev: v2.6
  git_depth: 1
  patches:
    - setup.patch

build:
  preserve_egg_dir: False
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

  missing_dso_whitelist:
    - $RPATH/libc.so.6  # [linux]
    - $RPATH/libm.so.6  # [linux]
    - $RPATH/libdl.so.2 # [linux]
    - $RPATH/libpthread.so.0 # [linux]
    - $RPATH/librt.so.1 # [linux]
    - $RPATH/libicuuc.so.60  #[linux]
    - $RPATH/libicui18n.so.60 #[linux]
    - $RPATH/libcudart.so.* #[linux]
    - $RPATH/cudart64_*.dll #[win]
    

requirements:
  build:
    - python
    - numpy {{ numpy }}
    - setuptools
    - cython
    - ripgrep
    - matplotlib
    - scipy
    - tqdm

  run:
    - python
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x.x') }}
    - matplotlib 
    - scipy
    - tqdm
    - libstdcxx-ng # [unix]
    - libgcc-ng # [unix]
    - vc 14 # [win]
    - cudatoolkit=11.8

about:
  home: https://github.com/CERN/TIGRE
  license:  BSD license
  summary: 'TIGRE: Tomographic Iterative GPU-based Reconstruction Toolbox'
