package:
  name: tigre
  version: {{ environ.get('GIT_DESCRIBE_TAG','v')[1:] }}

source:
  url: https://github.com/CERN/TIGRE/archive/refs/tags/v2.6.tar.gz
  sha256: a58104e62a84591ed59dc2f6a2be6ff7b1bec0ec6a47c159a17ed64f18895842
  patches:
    - setup.patch
    - cuda_home.patch

build:
  preserve_egg_dir: False
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  ignore_run_exports:
    - cudatoolkit

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}

  host:
    - python
    - numpy
    - setuptools
    - cython
    - ripgrep
    - cuda-version {{ cuda_compiler_version }}

  run:
    - python
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x.x') }}
    - matplotlib
    - scipy
    - tqdm
    - __cuda
    - {{ pin_compatible("cuda-version", min_pin="x.x", max_pin="x") }}

about:
  home: https://github.com/CERN/TIGRE
  license:  BSD license
  summary: 'TIGRE: Tomographic Iterative GPU-based Reconstruction Toolbox'
